### PR TITLE
Fix #150: dateRangeChange incorrectly called

### LINKED ISSUE #150: dateRangeChange incorrectly called when viewport is duration based
**Describe the bug**
When a viewport is duration based and is in live mode, Synchro Charts incorrectly calls on `dateRangeChange`, causing the widgets to rerender upon date range change events.

**To Reproduce**
1. Provide a duration for the viewport to a chart
2. Have some way of telling what the viewport is
3. See that viewport changes from duration to custom range with a start and end
4. See that the date range is changed upon every live tick

**Expected behavior**
`dateRangeChange` is expected to only be called on when gestures are applied. Live ticks for when viewport is in duration mode should not fire the `dateRangeChange` event.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Firefox
 - Version 91.10.0esr

**Additional context**
This was discovered while testing from IoT Application Kit

### PR DESCRIPTION
**Pull request by tjuranek**
## Overview
Fixes https://github.com/awslabs/synchro-charts/issues/150.

When in live mode, the viewportHandler tick cycle was passing the updated viewport back to the rendered chart. The logic was set to emit the `dateRangeChange` event any time the viewport changed. When in live mode this isn't the desired behavior so a flag was added to be able to check for that and block the event from being emitted.

## Tests
[Include a link to the passing GitHub action running the test suite here.]

## Legal
This project is available under the [Apache 2.0 License](http://www.apache.org/licenses/LICENSE-2.0.html).

### CODE REVIEW

**Comment by jmbuss** [comment]
Don't forget to squash all the commits into 1! :D

File: packages/synchro-charts/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx [hunk 1]
```diff
@@ -540,15 +540,18 @@ export class ScWebglBaseChart {
...
+      shouldBlockDateRangeChangedEvent,
+    }: { start: Date; end: Date; shouldBlockDateRangeChangedEvent?: boolean },
     hasDataChanged: boolean = false,
     hasSizeChanged: boolean = false,
     hasAnnotationChanged: boolean = false,
     shouldRerender: boolean = false
   ) => {
     const hasViewPortChanged = this.start.getTime() !== start.getTime() || this.end.getTime() !== end.getTime();
-    if (hasViewPortChanged) {
+    if (hasViewPortChanged && !shouldBlockDateRangeChangedEvent) {
```
Comment (boweihan) [inline packages/synchro-charts/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx:554]: Does this implementation work with Gestures (zoom in, zoom out, pan) for charts that start in live-mode? We want to make sure we aren't blocking change events for gestures for charts that start in live mode.

Comment (boweihan) [reply packages/synchro-charts/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx:554]: And by gestures, more specifically, i mean widget controls - https://synchrocharts.com/#/Introduction.

Comment (jmbuss) [inline packages/synchro-charts/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx:554]: Could we just check duration here similarly to how you are in `viewportHandler.ts`?

This way we wouldn't need to pass in any additional properties to `onUpdate`. It also aligns better with your test.

File: packages/synchro-charts/src/components/charts/sc-webgl-base-chart/utils.ts [hunk 2]
```diff
@@ -100,7 +100,7 @@ export const constructChartScene = ({
      */
     viewportGroup: viewport.group,
 
-    updateViewPort: ({ start, end }: { start: Date; end: Date }) => {
+    updateViewPort: ({ start, end, ...rest }: { start: Date; end: Date }) => {
```
Comment (jmbuss) [inline packages/synchro-charts/src/components/charts/sc-webgl-base-chart/utils.ts:103]: Could we add in the rest of the properties here in the type?

**Review by jmbuss — CHANGES_REQUESTED** [review]

File: packages/synchro-charts/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx (hunk 1 above)
Comment (tjuranek) [reply packages/synchro-charts/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx:554]: Yep! This works with gestures! We want to emit the `dateRangeChanged` event any time the viewport changes, unless we explicitly block it. When gestures happen we aren't blocking the event.

Comment (tjuranek) [reply packages/synchro-charts/src/components/charts/sc-webgl-base-chart/sc-webgl-base-chart.tsx:554]: That was my initial thought too, but it causes issues. There is a duration passed in any time that `onUpdate` is called, so we'd get false positives for the `isInLiveMode` check when we're performing a gesture or changes on charts in the same viewport group.

With this new property we can be explicit about blocking the event from firing in live mode without changing how other viewport updates work.

**Review by jmbuss — APPROVED** [review]
